export const FETCH_SUPERHEROES_SUCCESS = 'FETCH_SUPERHEROES_SUCCESS';
export const FETCH_SUPERHEROES_FAILURE = 'FETCH_SUPERHEROES_FAILURE';
export const SEARCH_SUPERHERO = 'SEARCH_SUPERHERO';
export const SORT_SUPERHEROES_ABILITY = 'SORT_SUPERHEROES_ABILITY';
export const SORT_SUPERHEROES_APPEARANCE = 'SORT_SUPERHEROES_APPEARANCE';
